{{- $fullName := include "em-processing.fullname" . -}}

{{- $dependsOnImage := .Values.global.dependsOn.image | default .Values.initcontainers.dependsOn.image -}}
{{- $dependsOnTag := .Values.global.dependsOn.tag | default .Values.initcontainers.dependsOn.tag -}}
{{- $dependsOnPullPolicy := .Values.global.dependsOn.imagePullPolicy | default "IfNotPresent" -}}
{{- $dependsOn := (printf "%s:%s" $dependsOnImage $dependsOnTag) -}}

{{- $applicationRegistry := .Values.global.enactor.image.registry | default .Values.image.registry -}}
{{- $applicationRepository := .Values.global.enactor.image.repository | default .Values.image.repository -}}

{{- $applicationTag :=  default (default .Values.global.enactor.image.tag .Chart.AppVersion) .Values.image.tag  -}}

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "em-processing.fullname" . }}
  labels:
    {{- include "em-processing.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  serviceName: {{ .Values.application.name }}
  selector:
    matchLabels:
      {{- include "em-processing.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "em-processing.selectorLabels" . | nindent 8 }}
        {{- range $labelName, $labelValue := $.Values.podLabels }}
        {{ $labelName | quote }}: {{ $labelValue | quote }}
        {{- end }}
    spec:
      enableServiceLinks: false
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "em-processing.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      automountServiceAccountToken: false
#      restartPolicy: Always
      terminationGracePeriodSeconds: 60

      initContainers:
        - name: depends-on
          image: {{ $dependsOn }}
          imagePullPolicy: {{ $dependsOnPullPolicy }}
          command:
            {{ .Values.global.dependsOn.command | toYaml | indent 12 | trim }}
          securityContext:
            {{- toYaml .Values.global.dependsOn.securityContext | nindent 12 }}
          resources:
            {{ .Values.global.dependsOn.resources| toYaml | indent 12 | trim}}
          env:
            - name: HOST
              value: {{ .Release.Name }}-mariadb
            - name: PORT
              value: {{ .Values.global.database.port | default 3306 | quote}}
            - name: INTERVAL
              value: '2'

      volumes:
        - name: enactor-data-{{ .Values.application.nameShort }}-home
          emptyDir: {}
      #- name: {{ .Values.application.nameShort }}-debuglog
      #  configMap:
      #    name: {{ .Values.application.nameShort }}-debuglog
      #- name: tomcatsetenv
      #  configMap:
      #    name: {{ .Values.application.nameShort }}-setenv  

      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{ if .Values.image.checksum }}
          image: "{{ $applicationRegistry }}/{{ $applicationRepository }}:{{ $applicationTag }}{{- printf "@%s" .Values.image.checksum }}"
          {{else}}
          image: "{{ $applicationRegistry }}/{{ $applicationRepository }}:{{ $applicationTag }}"
          {{end}}
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
          {{- range $key, $value := .Values.service.ports }}
          - name: {{ $key }}
            containerPort: {{ $value }}
            protocol: TCP
          {{- end }}

          {{ if .Values.probes.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: /
              port: http          
            periodSeconds: {{ .Values.probes.readinessProbe.periodSeconds }}
            failureThreshold: {{ .Values.probes.readinessProbe.failureThreshold }}
            initialDelaySeconds: {{ .Values.probes.readinessProbe.initialDelaySeconds }}
            successThreshold: {{ .Values.probes.readinessProbe.successThreshold }}
            timeoutSeconds: {{ .Values.probes.readinessProbe.timeoutSeconds }}
          {{end}}

          {{ if .Values.probes.startupProbe.enabled }}
          #startupProbe gives failureThreshold * periodSeconds seconds for the container to suceeed once then liveness probe kicks in
          #ideal for slow starting "un-predictable" containers such as EMP
          startupProbe: 
            httpGet:
              path: /
              port: http
            periodSeconds: {{ .Values.probes.startupProbe.periodSeconds }}
            failureThreshold: {{ .Values.probes.startupProbe.failureThreshold }}
            initialDelaySeconds: {{ .Values.probes.startupProbe.initialDelaySeconds }}
            successThreshold: {{ .Values.probes.startupProbe.successThreshold }}
            timeoutSeconds: {{ .Values.probes.startupProbe.timeoutSeconds }}
          {{end}}


          {{ if .Values.probes.livenessProbe.enabled }}
          #livenessProbe will first begin after startupProbe has had one successful 200 OK
          livenessProbe:
            httpGet:
              path: /
              port: http            
            periodSeconds: {{ .Values.probes.livenessProbe.periodSeconds }}
            failureThreshold: {{ .Values.probes.livenessProbe.failureThreshold }}
            initialDelaySeconds: {{ .Values.probes.livenessProbe.initialDelaySeconds }}
            successThreshold: {{ .Values.probes.livenessProbe.successThreshold }}
            timeoutSeconds: {{ .Values.probes.livenessProbe.timeoutSeconds }}
          {{end}}


          #lifecycle:
          #  preStop:
          #    exec:
          #      #command: ["/bin/bash", "-c", "PID=`pidof java` && kill -SIGTERM $PID && while ps -p $PID > /dev/null; do sleep 1; done;"] 
          #      command: ["/bin/bash", "-c", "/enactor/shared/tomcat/bin/catalina.sh stop 30 && sleep 30"]

          resources:
            {{- toYaml .Values.resources | nindent 12 }}

          volumeMounts:
            - name: enactor-data-{{ .Values.application.nameShort }}-home
              mountPath: /enactor/app/home
              {{- if .Values.persistentVolume.subPath }}
              subPath: {{ .Values.persistentVolume.subPath }}
              {{- end }}
            {{- if .Values.application.configMap.empDebugLog.enable }}
            - name:  emp-debuglog
              mountPath: /enactor/app/config/enactor-web-retail-processing.log.properties
              subPath: enactor-web-retail-processing.log.properties
            {{ end }}

            # common environmental variables
          envFrom:
          - configMapRef:
              name: {{ .Release.Name }}-envs-common-env
          - configMapRef:
              name: {{ .Release.Name }}-envs-common-em-env
          - configMapRef:
              name: {{ $fullName }}-envs-{{ .Values.application.nameShort }}-env

          env:
          - name: ENACTOR_JMX_SERVERHOSTNAME
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
                
          - name: ENACTOR_RMI_SERVERHOST
            valueFrom:
              fieldRef:
                fieldPath: status.podIP

          - name: ENACTOR_JMX_APPLICATIONID
            valueFrom:
              fieldRef:
                fieldPath: metadata.name

          {{- if .Values.global.enactor.extraVars }}
          {{ toYaml .Values.global.enactor.extraVars | nindent 10 }}
          {{- end }}

          {{- if .Values.application.extraVars }}
          {{ toYaml .Values.application.extraVars | nindent 10 }}
          {{- end }}


      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

  volumeClaimTemplates:
    - metadata:
        name: enactor-data-{{ .Values.application.nameShort }}-home
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage:  {{ .Values.persistentVolume.size }}  
        storageClassName: {{ .Values.global.persistence.storageClass | default .Values.persistentVolume.storageClass }}    
        {{- with .Values.persistentVolume.selector }}
        selector:
          {{- toYaml . | nindent 10 }}
        {{- end }}