apiVersion: v1
kind: Service
metadata:
  name: {{ include "em-cardauth.fullname" . }}
  labels:
    {{- include "em-cardauth.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- range $key, $value := .Values.service.ports }}
    - name: {{ $key }}
      port: {{ $value }}
      targetPort: {{ $key }}
      protocol: TCP
  {{- end }}
  selector:
    {{- include "em-cardauth.selectorLabels" . | nindent 4 }}
