global: 
  env: tmp
  clusterUrl: 'enactor-em.local'

  waitforit:
    image: 
      registry:
      repository: willwill/wait-for-it

  # -- DB Connection details
  # set to mariadb-0.mariadb if using the in-cluster database (see below) else
  # set DB connection details here. db_pass is encrypted in estate manager
  database:
    db_host: mariadb-0.mariadb
    db_port: 3306
    db_schema: enactorem_test


  # -- Pass extra environment variables to all enactor containers (override common vars).
  enactor:
    image:
      registry:
      tag:

    extraVars: []
      #- name: ENACTOR_DB_PASS
      #  value: "pass"
      #- name: ENACTOR_DB_USER
      #  value: "user"
      #- name: ENACTOR_AXIS2_PASSWORD
      #  value: "pass"
      #- name: ENACTOR_AXIS2_USER
      #  value: "admin"
      #- name: ENACTOR_TASK_SYSTEMPASSWORD
      #  value: "pass"
      #- name: ENACTOR_TASK_SYSTEMUSER
      #  value: "taskadmin"

config:
  common:
    processSet: null

  modules:
    crm: false
    customerCollection: false
    inventory: false
    order: false
    processing: true
    repair: false
    timeAttendance: false

  java:
    country: null
    timezone: null

# Enactor Configuration
  
em-processing:
  deploy: true
  ingress:
    enabled: true
  persistentVolume:
    persistentStorageClassName: managed-nfs-storage-retain
    size: "100Gi"
  sidecars:
    empwatch:
      deploy: true
      tag: '1.2.0'

em-application:
  deploy: true
  ingress:
    enabled: true
  persistentVolume:
    persistentStorageClassName: managed-nfs-storage-retain
    size: "5Gi"

em-services:
  deploy: true
  ingress:
    enabled: true

em-terminalmanagement:
  deploy: true
  ingress:
    enabled: false

em-adyenintegrationservice:
  deploy: true
  ingress:
    enabled: true

em-cardauth:
  deploy: true

em-reports:
  deploy: true


# Thirdparty Configuration
mariadb:
  deploy: true
  auth:
    rootPassword: "toor"
    database: "enactorem_test"
    username: "enactor_app"
    password: "p4ssw0rd"
  primary:
    persistence:
      size: "25Gi"
    configuration: |
      [mysqld]
      skip-name-resolve
      explicit_defaults_for_timestamp
      basedir=/opt/bitnami/mariadb
      plugin_dir=/opt/bitnami/mariadb/plugin
      port=3306
      socket=/opt/bitnami/mariadb/tmp/mysql.sock
      tmpdir=/opt/bitnami/mariadb/tmp
      max_allowed_packet=16M
      bind-address=*
      pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid
      log-error=/opt/bitnami/mariadb/logs/mysqld.log

      slow_query_log=0
      slow_query_log_file=/opt/bitnami/mariadb/logs/mysqld.log
      long_query_time=10.0

      character-set-server  = utf8mb4
      collation-server      = utf8mb4_general_ci
      transaction_isolation = READ-COMMITTED
      lower_case_table_names = 1

      [client]
      port=3306
      socket=/opt/bitnami/mariadb/tmp/mysql.sock
      default-character-set=UTF8
      plugin_dir=/opt/bitnami/mariadb/plugin

      [manager]
      port=3306
      socket=/opt/bitnami/mariadb/tmp/mysql.sock
      pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid
    